### ISSUE TITLE
ERROR: Failed to retrieve an on-air date.

### ISSUE THREAD

**Issue by oratosa** [oratosa/PlaylistMaker#4]
> severity: "ERROR"
textPayload: "Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/functions_framework/__init__.py", line 174, in view_func
    function(event)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/functions_framework/__init__.py", line 70, in wrapper
    return func(*args, **kwargs)
  File "/workspace/main.py", line 28, in handler
    on_air_date = scraper.get_on_air_date(date_html)
  File "/workspace/main.py", line 81, in get_on_air_date
    text = html.get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'"
timestamp: "2023-05-13T16:00:08.182998Z"

**Comment by oratosa** [comment]
Checked the test passed.

> 
> 
> 
>  (env) Laptop813:weekend_sunshine asotaro$ pytest test_main.py::test_get_on_air_date
> ========================================================= test session starts =========================================================
> platform darwin -- Python 3.9.16, pytest-7.3.1, pluggy-1.0.0
> rootdir: /Users/asotaro/codes/weekend_sunshine
> collected 1 item                                                                                                                      
> 
> test_main.py .                                                                                                                  [100%]
> 
> ========================================================== 1 passed in 1.80s ==========================================================
> (env) Laptop813:weekend_sunshine asotaro$ pytest test_main.py::test_get_on_air_date
> ========================================================= test session starts =========================================================
> platform darwin -- Python 3.9.16, pytest-7.3.1, pluggy-1.0.0
> rootdir: /Users/asotaro/codes/weekend_sunshine
> collected 1 item                                                                                                                      
> 
> test_main.py .                                                                                                                  [100%]
> 
> ========================================================== 1 passed in 1.60s ==========================================================
