### ISSUE TITLE
It hasn't created a new playlist since 2024-04-20.

### ISSUE THREAD

**Issue by oratosa** [oratosa/PlaylistMaker#8]
The value of class_ was changed.

> 2024-04-20 09:00:16.045 PDT
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/functions_framework/__init__.py", line 174, in view_func
    function(event)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/functions_framework/__init__.py", line 70, in wrapper
    return func(*args, **kwargs)
  File "/workspace/main.py", line 27, in handler
    date_html = scraper.html.find("div", class_="article-text").find("p")
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by oratosa** [comment]
> 2024-07-13 09:00:09.707 PDT
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/functions_framework/__init__.py", line 178, in view_func
    function(event)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/functions_framework/__init__.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/workspace/main.py", line 44, in handler
    uris = playlistmaker.generate_track_id_list(playlist_for_spotify_input)
  File "/workspace/main.py", line 162, in generate_track_id_list
    uri = self.get_spotify_track_info(track, artist, album)
  File "/workspace/main.py", line 187, in get_spotify_track_info
    and album_name in album
TypeError: argument of type 'NoneType' is not iterable

This error was also resolved in the branch i_8 by fixing a bug related to regular expression.
